services:
  - type: web
    name: abu-malik-services      # غير الاسم إذا أردت
    runtime: python
    plan: free                     # أو starter حسب حسابك
    build:
      commands:
        - apt-get update
        - apt-get install -y gfortran libblas-dev liblapack-dev
        - pip install --upgrade pip
        - pip install -r requirements.txt
    start:
      command: python3 app.py
