kind = "api"
previewPath = "/"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Flask App"
paths = ["/"]

[services.development]
run = "python3 /home/runner/workspace/app.py"

[services.production]

[services.production.run]
args = ["python3", "/home/runner/workspace/app.py"]

[services.production.run.env]
PORT = "5000"
